### ISSUE TITLE
Support nodes in subfolder

### ISSUE THREAD

**Issue by tadatuta** [enb-bem/enb-bem-docs#46]
If nodes are in subfolder, code at https://github.com/enb-bem/enb-bem-docs/blob/master/lib/techs/meta-json.js#L11 and on https://github.com/enb-bem/enb-bem-docs/blob/master/lib/techs/meta-json.js#L18 fails.

Relats to https://github.com/enb-bem/enb-bem-examples/pull/20

**Comment by blond** [comment]
The problem occurs when the option `destPath` is complex path?

Works well:

```js
destPath: 'desktop.examples'
```

Falls with error:

```js
destPath: 'path/to/desktop.examples'
```

**Comment by tadatuta** [comment]
yes
