### ISSUE TITLE
Make absolute path on img in docs

### ISSUE THREAD

**Issue by gela-d** [enb-bem/enb-bem-docs#52]
If we have relative link on img in some doc, we have to build absolute path to image on github.
___
Если у нас в документации встречается относительная ссылка на картинку, нужно ее делать абсолютной на гитхаб.

**Comment by arikon** [comment]
+1

**Comment by gela-d** [comment]
Еще один кейс для абсолютной ссылки, когда у нас в одном блоке есть ссылка на  js другого блока `../alert/alert.examples/10-simple.blocks/button/_message/button_message_block.js`. Думаю, такая ссылка тоже хорошо бы становилась абсолютной на гитхаб сразу.

**Comment by blond** [comment]
Этот пакет должен работать с данными, он ничего не должен знать ни про гитхаб, ни про что-то ещё.

**Comment by gela-d** [comment]
@blond спасибо, действительно.

@arikon тогда, для того чтобы на сайте также корректно все отображалось, на самом гитхабе нужно делать эти ссылки абсолютные. Пока что других вариантов не вижу.

**Comment by blond** [comment]
@gela-d Почему нельзя делать это в `bem-data-source`?

**Comment by gela-d** [comment]
Поговорили голосом с @blond, нельзя это делать в bem-data-source.
@arikon я сейчас в задаче отпишусь насчет варианта решения.
